Resources:
  reactmarkdownwebuidevbucket5FC59F12:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - ""
          - - react-markdown-web-ui-dev-
            - Ref: AWS::AccountId
            - "-"
            - Ref: AWS::Region
      WebsiteConfiguration:
        IndexDocument: index.html
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: react-markdown-web-ui-dev/react-markdown-web-ui-dev-bucket/Resource
  reactmarkdownwebuidevbucketPolicy8D752C0E:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: reactmarkdownwebuidevbucket5FC59F12
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - reactmarkdownwebuidevbucket5FC59F12
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: react-markdown-web-ui-dev/react-markdown-web-ui-dev-bucket/Policy/Resource
  reactmarkdownwebuidevcdnCFDistribution7E7766EF:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: origin1
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName:
              Fn::GetAtt:
                - reactmarkdownwebuidevbucket5FC59F12
                - RegionalDomainName
            Id: origin1
            S3OriginConfig: {}
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
    Metadata:
      aws:cdk:path: react-markdown-web-ui-dev/react-markdown-web-ui-dev-cdn/CFDistribution
  reactmarkdownwebuidevbucketdeploymentCustomResourceB31A2EB8:
    Type: Custom::CDKBucketDeployment
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536
          - Arn
      SourceBucketNames:
        - Ref: AssetParametersa5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590aS3BucketB3F4DA56
      SourceObjectKeys:
        - Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590aS3VersionKeyE76D1104
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590aS3VersionKeyE76D1104
      DestinationBucketName:
        Ref: reactmarkdownwebuidevbucket5FC59F12
      DistributionId:
        Ref: reactmarkdownwebuidevcdnCFDistribution7E7766EF
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: react-markdown-web-ui-dev/react-markdown-web-ui-dev-bucket-deployment/CustomResource/Default
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: react-markdown-web-ui-dev/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Ref: AssetParametersa5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590aS3BucketB3F4DA56
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Ref: AssetParametersa5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590aS3BucketB3F4DA56
                    - /*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - reactmarkdownwebuidevbucket5FC59F12
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - reactmarkdownwebuidevbucket5FC59F12
                        - Arn
                    - /*
          - Action:
              - cloudfront:GetInvalidation
              - cloudfront:CreateInvalidation
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      Roles:
        - Ref: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: react-markdown-web-ui-dev/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/DefaultPolicy/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0S3Bucket88A20322
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0S3VersionKey5726B1E8
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0S3VersionKey5726B1E8
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
          - Arn
      Runtime: python3.6
      Timeout: 900
    DependsOn:
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: react-markdown-web-ui-dev/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/Resource
      aws:asset:path: asset.85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0.zip
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.47.0,@aws-cdk/assets=1.47.0,@aws-cdk/aws-certificatemanager=1.47.0,@aws-cdk/aws-cloudfront=1.47.0,@aws-cdk/aws-cloudwatch=1.47.0,@aws-cdk/aws-ec2=1.47.0,@aws-cdk/aws-events=1.47.0,@aws-cdk/aws-iam=1.47.0,@aws-cdk/aws-kms=1.47.0,@aws-cdk/aws-lambda=1.47.0,@aws-cdk/aws-logs=1.47.0,@aws-cdk/aws-s3=1.47.0,@aws-cdk/aws-s3-assets=1.47.0,@aws-cdk/aws-s3-deployment=1.47.0,@aws-cdk/aws-sqs=1.47.0,@aws-cdk/aws-ssm=1.47.0,@aws-cdk/cloud-assembly-schema=1.47.0,@aws-cdk/core=1.47.0,@aws-cdk/cx-api=1.47.0,@aws-cdk/region-info=1.47.0,jsii-runtime=node.js/v12.18.3
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0S3Bucket88A20322:
    Type: String
    Description: S3 bucket for asset "85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0"
  AssetParameters85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0S3VersionKey5726B1E8:
    Type: String
    Description: S3 key for asset version "85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0"
  AssetParameters85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0ArtifactHash877EFA91:
    Type: String
    Description: Artifact hash for asset "85263806834b4abe18b7438876d0e408b131a41c86272285f069bb9fa96666f0"
  AssetParametersa5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590aS3BucketB3F4DA56:
    Type: String
    Description: S3 bucket for asset "a5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590a"
  AssetParametersa5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590aS3VersionKeyE76D1104:
    Type: String
    Description: S3 key for asset version "a5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590a"
  AssetParametersa5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590aArtifactHashCD91485F:
    Type: String
    Description: Artifact hash for asset "a5a13f97e68e8a439a6d740726e3cb96ee5dde993db3fe8275570effff39590a"
Outputs:
  CloudfrontDistributionDomainOutput:
    Value:
      Fn::GetAtt:
        - reactmarkdownwebuidevcdnCFDistribution7E7766EF
        - DomainName
    Export:
      Name: CloudfrontDistribution
  CloudfrontDistributionIdOutput:
    Value:
      Ref: reactmarkdownwebuidevcdnCFDistribution7E7766EF
    Export:
      Name: CloudfrontDistributionId
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

