env:
  node: true
  commonjs: true
  es2020: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'eslint-config-prettier'
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
