version: '3'
services:
  tests:
    build:
      context: ../../
      dockerfile: packages/api/Dockerfile
    command: npx npm-run-all bootstrap _hang
    depends_on:
      - postgres_test
    environment:
      DATABASE_URL: postgres://react_markdown_api_test_user:react_markdown_api_test_password@postgres_test:5432/react_markdown_api_test
    volumes:
      - ../../:/usr/src/app

  postgres_test:
    image: postgres:10.4
    ports:
      - '45432:5432'
    environment:
      POSTGRES_USER: react_markdown_api_test_user
      POSTGRES_PASSWORD: react_markdown_api_test_password
      POSTGRES_DB: react_markdown_api_test
      POSTGRES_PORT: 5432
